[package]
name = "learn-async"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.34"
futures = "0.3.30"
inquire = "0.7.0"
reqwest = "0.11.24"
tokio = { version = "1.36.0", features = ["full"] }
